version: '3'

services:
  postgres:
    image: postgres:12.2-alpine
    container_name: hexa_kotlin_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hexagonal_kotlin
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    networks:
      - hexa_kotlin_network

networks:
  hexa_kotlin_network:
    driver: bridge
