spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/hexagonal_kotlin
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/hexagonal_kotlin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
